# Generated by Django 4.2.5 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='qwerqwer', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
