version: '2'

services:
    nginx:
        container_name: nginx
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/server/django_static
            - ./docker/nginx/development:/etc/nginx/conf.d
            - media_volume:/app/backend/server/media
        depends_on: 
            - backend
    backend:
        container_name: django_rest
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - .:/app
            - static_volume:/app/backend/server/django_static
            - media_volume:/app/backend/server/media
        expose:
            - 8000
    frontend:
        container_name: next_js
        restart: unless-stopped
        build:
          context: .
          dockerfile: ./docker/frontend/Dockerfile
        volumes:
          - node_modules:/app/frontend/node_modules
        expose:
          - 3000

volumes:
    static_volume:
    media_volume:
    node_modules:
