import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/redux/provider";
import { Navbar, Footer } from "@/components/common";
import Setup from "@/components/common/utils/Setup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laced",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          <Navbar />
          <div className="bg-[#FAF9F8]">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
